spring.application.name=CommunicationService

#server.port=8080
#server.error.whitelabel.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/communication_service
spring.datasource.username=root
spring.datasource.password=aj@12
spring.jpa.hibernate.ddl-auto=update
