spring.application.name=user-service
server.port=8080

# Database Configurations
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Eureka Configurations
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Enable Actuator (Optional)
management.endpoints.web.exposure.include=health,metrics

spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


#spring.application.name=user-service

#server.port=8080


#spring.datasource.url= jdbc:h2:mem:userdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update



#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

#spring.security.user.name= admin
#spring.security.user.password= admin123
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

